# Generated by Django 4.0.5 on 2022-06-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correo',
            old_name='corre_admin',
            new_name='correo_admin',
        ),
    ]
